easy_admin:
   site_name: '<img src="../../assets/images/studiotibo-logo-wit.png"/>'
   design:
     form_theme:
       - '@EasyAdmin/form/bootstrap_4.html.twig'
       - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
     assets:
       favicon: '../../assets/images/favicon-32x32.png'
       css:
         - '../../assets/css/style.css'

     menu:
       - label: 'Afbeeldingen'
         icon: 'image'
         children: ['Works', 'Category']
       - label: 'Paginaonderdelen aanpassen'
         icon: 'file'
         children: ['Sections', 'Textfield', 'Pagina']
       - label: 'Lessen en evenementen'
         icon: 'calendar'
         children: ['Lessen', 'Events']
       - label: 'Mensen die contact willen'
         icon: 'envelope'
         children: ['Contact']
       - label: 'Users toevoegen/verwijderen'
         icon: 'users'
         children: ['User']

   user:
     name_property_path: 'voornaam'
     display_avatar: false
   list:
     actions:
       - { name: 'show', icon: 'info-circle' }
       - { name: 'edit', icon: 'pencil' }
       - { name: 'delete', icon: 'trash-alt' }
   entities:
       # List the entity class name you want to manage
     Works:
       class: App\Entity\Works
       label: 'Werken'
       help: 'Een lijst van al jouw werken en waar ze toe behoren'
       form:
         fields:
           - {property: 'naam', label: 'Naam Werk'}
           - {property: 'imageFile', type: 'vich_image' }
           - {property: 'beschrijving', label: 'Beschrijving afbeelding'}
           - {property: 'category', label: 'Categorie'}
           - {property: 'userId', label: 'User'}
       list:
         fields:
           - {property: 'naam', label: 'Naam Werk'}
           - {property: 'filename', label: 'Afbeelding', base_path: '/assets/images', type: 'image'}
           - {property: 'category', label: 'Categorie'}
     User:
       class: App\Entity\User
       label: 'Gebruikers'
       help: 'Hier kan je een lijst zien van alle gebruikers die hierop kunnen werken.'
       form:
         fields:
           - {property: 'voornaam'}
           - {property: 'naam'}
           - {property: 'email'}
           - {property: 'password', label: 'Wachtwoord', type: 'password'}
       list:

         fields:
           - voornaam
           - naam
           - email

     Category:
        class: App\Entity\Category
        label: 'Categorieën'
        help: 'Bekijk hier alle categorieën.'
        form:
          fields:
            - {property: 'cat_name' , label: 'Categorienaam'}
            - {property: 'imageFile', type: 'vich_image' }
        list:
          sort: ['id', 'ASC']
          fields:
            - {property: 'cat_name' , label: 'Categorienaam'}
            - {property: 'cat_img' , label: 'Header van de categorie',  base_path: '/assets/images', type: 'image'}

     Events:
        class: App\Entity\Events
        label: 'Evenementen'
        help: 'Maak hier jouw evenementen aan.'
        form:
          fields:
            - {property: 'naam' , label: 'Naam evenement'}
            - {property: 'imageFile' , label: 'Afbeelding evenement', type: 'vich_image'}
            - {property: 'beschrijving' , label: 'Beschrijving'}
            - {property: 'link' , label: 'website-url'}
            - {property: 'adres' , label: 'Adres'}
            - {property: 'postcode' , label: 'Postcode'}
            - {property: 'locatie' , label: 'Gemeente'}
            - {property: 'event_start' , label: 'Startdatum', type: 'datetime'}
            - {property: 'event_end' , label: 'Einddatum', type: 'datetime'}
            - {property: 'userId', label: 'User'}
        list:
          sort: ['id', 'ASC']
          fields:
            - {property: 'naam' , label: 'Naam evenement'}
            - {property: 'img' , label: 'Afbeelding evenement', base_path: '/assets/images', type: 'image'}
            - {property: 'locatie' , label: 'Gemeente'}
            - {property: 'event_start' , label: 'Startdatum', type: 'datetime'}
            - {property: 'event_end' , label: 'Einddatum', type: 'datetime'}


     Lessen:
        class: App\Entity\Lessen
        label: 'Lessenrooster'
        help: 'Maak hier jouw lessen aan.'
        form:
          fields:
            - {property: 'datum' , label: 'Dag van de les'}
            - {property: 'klasgroep' , label: 'Klasgroep'}
            - {property: 'locatie' , label: 'Waar vindt het plaats?'}
            - {property: 'adres' , label: 'Adres'}
            - {property: 'postcode' , label: 'Postcode'}
            - {property: 'gemeente' , label: 'Gemeente'}

        list:
          sort: ['id', 'ASC']
          fields:
            - {property: 'datum' , label: 'Dag van de les'}
            - {property: 'klasgroep' , label: 'Klasgroep'}
            - {property: 'locatie' , label: 'Waar vindt het plaats?'}
            - {property: 'adres' , label: 'Adres'}
            - {property: 'postcode' , label: 'Postcode'}
            - {property: 'locatie' , label: 'Gemeente'}


     Pagina:
        class: App\Entity\Pagina
        label: 'Paginas Website'
        help: 'Maak hier jouw pagina aan'
        form:
          fields:
            - {property: 'pagina_naam' , label: 'Naam van de pagina'}


        list:
          sort: ['id', 'ASC']
          fields:
            - {property: 'pagina_naam' , label: 'Naam van de pagina'}

     Sections:
        class: App\Entity\Sections
        label: 'Paginaonderdelen'
        help: 'Maak/bekijk hier jouw paginaonderdelen'
        form:
          fields:
            - {property: 'naam' , label: 'Naam onderdeel'}
            - {property: 'pagina' , label: 'Op welke pagina?'}
            - {property: 'h1_titel' , label: 'Hoofdtitel'}
            - {property: 'userId' , label: 'Door wie?'}

        list:
          sort: ['id', 'ASC']
          fields:
            - {property: 'naam' , label: 'Naam onderdeel'}
            - {property: 'pagina' , label: 'Op welke pagina?'}
            - {property: 'h1_titel' , label: 'Hoofdtitel'}

     Textfield:
        class: App\Entity\Textfield
        label: 'Tekstvelden'
        help: 'Maak/bekijk hier jouw tekstvelden die je op de verschillende onderdelen hebt gezet'
        form:
          fields:
            - {property: 'title' , label: 'Titel tekst'}
            - {property: 'sectionId' , label: 'Op welke paginaonderdeel?'}
            - {property: 'tekst' , label: 'De uitgebreide tekst', type: 'fos_ckeditor'}
            - {property: 'link' , label: 'Link naar iets?'}
            - {property: 'imageFile', type: 'vich_image' }

        list:
          sort: ['id', 'ASC']
          fields:
            - {property: 'title' , label: 'Titel tekst'}
            - {property: 'tekst' , label: 'De uitgebreide tekst'}
            - {property: 'link' , label: 'Link naar iets?'}
            - {property: 'image' , label: 'Een afbeelding', base_path: '/assets/images', type: 'image'}



     Contact:
        class: App\Entity\Contact
        label: 'Contact'
        disabled_actions: ['new']
        help: 'Een lijst van alle mensen die contact met jou willen opnemen'
        list:
          fields:
            - {property: 'naam', label: 'Naam contactpersoon'}
            - {property: 'email', label: 'Hun e-mailadres', type: 'email'}
            - {property: 'vraag', label: 'Hun vraag', type: 'text'}
            - {property: 'created_at', label: 'Verzenddatum', type: 'date'}
            - {property: 'is_answered', label: 'Contact opgenomen?', type: 'toggle'}
